spring.data.mongodb.uri=${workoutDiaryMongoURI}
spring.data.mongodb.database=${workoutDiaryMongoDB}
spring.data.mongodb.auto-index-creation = true
server.port=10000

# jwtSecret used in JwtUtils
WorkoutDiary.app.jwtSecret=${workoutDiaryJwtSecret} 
WorkoutDiary.app.jwtExpirationMs=3600000

# ========== Bunch of logging level ============
# logging.level.root=debug
logging.level.com.thirteenseven.workoutdiary.filter=debug